### ISSUE TITLE
Where's the css?

### ISSUE THREAD

**Issue by MichaelJCole** [classcraft/classcraft-meteor-wkhtmltopdf#2]
Hi, I have this package in my meteor project.

`twbs:bootstrap`

How do I get to the bootstrap.css at runtime? 

Thanks!

**Comment by choyweston** [comment]
A path to the css in the html head : 

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    	<meta content="text/html; charset=utf-8" http-equiv="content-type">
    	<link href="path/to/css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    	<body>
    		... stuff goes here. 
    	</body>
    </html>

Your packages css is probably aggregated into the main css of your app.
