### ISSUE TITLE
corrupt pdf as output

### ISSUE THREAD

**Issue by Christilut** [classcraft/classcraft-meteor-wkhtmltopdf#3]
Hi,

I can't seem to get this package to work.

If I do 
```coffeescript
generatePDF = (html, {}) ->
  wkhtmltopdf(html, (code, signal) ->
    console.log 'worked!', fs.readFileSync('out.pdf').toString()
  ).pipe(fs.createWriteStream('out.pdf'))
```
then I get no output at all, no message logged either.

If I try
```coffeescript
  wkhtmltopdf(html, (code, signal) ->
    console.log 'worked!', fs.readFileSync('out.pdf').toString()
  ).pipe(fs.createWriteStream('out.pdf'))
```
Then I get a 3kb corrupt PDF. I guess because the method isnt able to finish in time.

What am I doing wrong?

**Comment by choyweston** [comment]
You need to have external binaries installed on your server. Is that the case?

**Comment by Christilut** [comment]
Yes I installed the [wkhtmltopdf](http://wkhtmltopdf.org/downloads.html) Linux (Ubuntu Trusty) 64bit on my 14.04 VPS

**Comment by choyweston** [comment]
Wkhtml is pretty finnicky. If the html doesn't compile properly or if you don't have the fonts you need server side, it'll corrupt.

**Comment by Christilut** [comment]
Got it working!  
Turns out the PDF generated was good but something went wrong during file transfer and kept corrupting it. Sending it over SCP now and the file is good.

Thanks for the help, got me in the right direction :)

**Comment by choyweston** [comment]
Amazing! With your project :)
