### ISSUE TITLE
wkhtmltopdf: error [Error: /bin/sh: 1: wkhtmltopdf: not found]

### ISSUE THREAD

**Issue by rudza** [classcraft/classcraft-meteor-wkhtmltopdf#5]
`wkhtmltopdf: error [Error: /bin/sh: 1: wkhtmltopdf: not found]`

I get this error, when trying to use the package.

**Comment by choyweston** [comment]
You have to install the binary on your server.

**Comment by benjbmc** [comment]
Same error

> sh: 1: wkhtmltopdf: not found

And I'm getting `/usr/bin/wkhtmltopdf` with this command: `which wkhtmltopdf`
It means binary is installed, no ?
