### ISSUE TITLE
wkhtmltopdf: error [Error: Exit with code 1 due to http error: 1203]

### ISSUE THREAD

**Issue by rudza** [classcraft/classcraft-meteor-wkhtmltopdf#6]
I got this error: ```wkhtmltopdf: error [Error: Exit with code 1 due to http error: 1203]
```

PDF returned looks fine, but it still returns this error.

**Comment by choyweston** [comment]
Since this is just wrapper for this : https://www.npmjs.com/package/wkhtmltopdf, I'd recommend installing it directly from NPM, instead of using this.
